config/routes.rb
HongKongPublicHolidays::Application.routes.draw do
  get "home/index"

  resources :hk_public_holidays

  devise_for :users

  root :to => "home#index"
  match 'home' => 'home#index', :as => :home
  

end

app/models/hk_public_holiday.rb
class HkPublicHoliday < ActiveRecord::Base
  validates_uniqueness_of :date
  
  def self.all_years
    HkPublicHoliday.select("year").group("year").map(&:year).sort
  end
  
  def self.to_csv_response
    something = FasterCSV.generate do |csv|
      csv << ["Year", "Date"]
      
      self.scoped.each do |holiday|
        csv << [ holiday.year, holiday.date ]
      end
      
    end

    something
  end
    
  scope :by_year, lambda {|year|
    where(:year => year).order("date ASC")
    }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def render_csv(filename = nil)
    filename ||= params[:action]
    filename += '.csv'

    if request.env['HTTP_USER_AGENT'] =~ /msie/i
      headers['Pragma'] = 'public'
      headers["Content-type"] = "text/plain" 
      headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
      headers['Content-Disposition'] = "attachment; filename=\"#{filename}\"" 
      headers['Expires'] = "0" 
    else
      headers["Content-Type"] ||= 'text/csv'
      headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" 
    end

    render :layout => false
  end

end

app/controllers/hk_public_holidays_controller.rb
class HkPublicHolidaysController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /hk_public_holidays
  # GET /hk_public_holidays.xml
  def index
    @hk_public_holidays = HkPublicHoliday.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hk_public_holidays }
    end
  end

  # GET /hk_public_holidays/1
  # GET /hk_public_holidays/1.xml
  def show
    @hk_public_holiday = HkPublicHoliday.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hk_public_holiday }
    end
  end

  # GET /hk_public_holidays/new
  # GET /hk_public_holidays/new.xml
  def new
    @hk_public_holiday = HkPublicHoliday.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hk_public_holiday }
    end
  end

  # GET /hk_public_holidays/1/edit
  def edit
    @hk_public_holiday = HkPublicHoliday.find(params[:id])
  end

  # POST /hk_public_holidays
  # POST /hk_public_holidays.xml
  def create
    @hk_public_holiday = HkPublicHoliday.new(params[:hk_public_holiday])

    respond_to do |format|
      if @hk_public_holiday.save
        format.html { redirect_to(@hk_public_holiday, :notice => 'Hk public holiday was successfully created.') }
        format.xml  { render :xml => @hk_public_holiday, :status => :created, :location => @hk_public_holiday }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hk_public_holiday.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hk_public_holidays/1
  # PUT /hk_public_holidays/1.xml
  def update
    @hk_public_holiday = HkPublicHoliday.find(params[:id])

    respond_to do |format|
      if @hk_public_holiday.update_attributes(params[:hk_public_holiday])
        format.html { redirect_to(@hk_public_holiday, :notice => 'Hk public holiday was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hk_public_holiday.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hk_public_holidays/1
  # DELETE /hk_public_holidays/1.xml
  def destroy
    @hk_public_holiday = HkPublicHoliday.find(params[:id])
    @hk_public_holiday.destroy

    respond_to do |format|
      format.html { redirect_to(hk_public_holidays_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @year = params[:year]
    if @year
      @holidays = HkPublicHoliday.where(:year => @year)
    else
      @holidays = HkPublicHoliday.scoped
    end
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @holidays, :except => [:created_at, :id, :updated_at] }
      format.csv  {
        send_data(@holidays.to_csv_response, :filename => "hk_public_holidays#{@year}.csv", :disposition => "inline", :type => "csv")
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hk_public_holidays_helper.rb
module HkPublicHolidaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def all_years
    HkPublicHoliday.all_years
  end
end

app/views/hk_public_holidays/_form.html.haml
= form_for @hk_public_holiday do |f|
  -if @hk_public_holiday.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hk_public_holiday.errors.count, "error")} prohibited this hk_public_holiday from being saved:"
      %ul
        - @hk_public_holiday.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :year
    = f.text_field :year
  .field
    = f.label :date
    = f.date_select :date
  .actions
    = f.submit 'Save'

app/views/hk_public_holidays/edit.html.haml
%h1 Editing hk_public_holiday

= render 'form'

= link_to 'Show', @hk_public_holiday
\|
= link_to 'Back', hk_public_holidays_path

app/views/hk_public_holidays/index.html.haml
%h1 Listing hk_public_holidays

%table
  %tr
    %th Year
    %th Date
    %th
    %th
    %th

  - @hk_public_holidays.each do |hk_public_holiday|
    %tr
      %td= hk_public_holiday.year
      %td= hk_public_holiday.date
      %td= link_to 'Show', hk_public_holiday
      %td= link_to 'Edit', edit_hk_public_holiday_path(hk_public_holiday)
      %td= link_to 'Destroy', hk_public_holiday, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Hk public holiday', new_hk_public_holiday_path

app/views/hk_public_holidays/new.html.haml
%h1 New hk_public_holiday

= render 'form'

= link_to 'Back', hk_public_holidays_path

app/views/hk_public_holidays/show.html.haml
%p#notice= notice

%p
  %b Year:
  = @hk_public_holiday.year
%p
  %b Date:
  = @hk_public_holiday.date

= link_to 'Edit', edit_hk_public_holiday_path(@hk_public_holiday)
\|
= link_to 'Back', hk_public_holidays_path

app/views/home/index.html.haml
.block#text
  .content
    .inner
      #helper-links
        = link_to("CSV Format", home_url({:format => "csv"}.merge(request.parameters)))
        = link_to("XML Format", home_url({:format => "xml"}.merge(request.parameters)))
      - if @year
        %h2= "Year #{@year}"
      %table
        %tr
          %th Date
          %th Description

        - @holidays.each do |hk_public_holiday|
          %tr
            %td= hk_public_holiday.date
            %td= hk_public_holiday.description

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:id => "page_favicon", :href => "/favicon.ico", :rel =>"icon", :type =>"image/x-icon"}
    %title Hong Kong Public Holidays
    = stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/warehouse/style", "web-app-theme/override"
    = javascript_include_tag :defaults
    = csrf_meta_tag

    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-25533354-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  %body
    #container
      #header
        %h1
          %a{:href => "/"} Hong Kong Public Holidays
        =image_tag("/images/calendar.png", :height => "80px")
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        #user-navigation
          %ul.wat-cf
            / cache this year menu 
            - all_years.each do |year|
              %li
                = link_to year, home_url(:year => year), :class => year < Date.today.year ? "past-year" : ""
            %li
              = link_to "All", home_url
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Data source:
                =image_tag("http://www.gov.hk/favicon.ico")
                =link_to "Hong Kong Gov Website", "http://www.gov.hk/en/about/abouthk/holiday/"
            .block
              %p
                Source Code available at
                =image_tag("http://github.com/favicon.ico")
                =link_to "Github", "http://github.com/3dd13"
            .block
              %p
                written in Ruby On Rails, by 
                =image_tag("http://3dd13.me/favicon.ico")
                =link_to "3dd13", "http://3dd13.me"
        #sidebar
          = yield :sidebar

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hong Kong Public Holidays</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/warehouse/style", "web-app-theme/override", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>            
    </div>
  </div>
</body>
</html>